# Site Configuration
title: ${basic,hyper,native,viper}HTML

# Site URL
url: https://viperhtml.js.org
baseurl: ''

# Defaults
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
